name: update-snapshot
on:
  schedule:
    - cron: '*/5 * * * *'    # every 5 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install websockets pandas ccxt
      - run: python cross_exchange_agg.py
      - run: |
          git config --global user.email "bot@example.com"
          git config --global user.name  "snapshot-bot"
          git add agg_snapshot.csv
          git commit -m "auto $(date -u +'%H:%M:%S')" || echo "no change"
          git push
