name: snapshot-once

on:
  workflow_dispatch:    # manual button
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      # 1) Checkout using GITHUB_TOKEN for push
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # this tells checkout to configure git with GITHUB_TOKEN

      # 2) Set up Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3) Install deps
      - name: Install dependencies
        run: pip install requests

      # 4) Generate the CSV
      - name: Run snapshot_once.py
        run: python snapshot_once.py

      # 5) Commit & push the CSV if it changed
      - name: Commit & push agg_snapshot.csv
        run: |
          # configure commit user
          git config user.name "snapshot-bot"
          git config user.email "bot@example.com"
          # only commit if there are changes
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add agg_snapshot.csv
            git commit -m "auto snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
