name: snapshot-once     # Visible name in the Actions tab

on:
  workflow_dispatch:    # Adds the “Run workflow” button
  schedule:             # Automatic run every 5 minutes (UTC)
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 4          # Auto-kills job if it hangs >4 min

    steps:
    # 1) Pull your repository
    - uses: actions/checkout@v4

    # 2) Install Python 3.10
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3) Install Python dependencies
    - name: Install dependencies
      run: pip install requests           # add pandas/websockets here if needed

    # 4) Generate the CSV snapshot
    - name: Run snapshot_once.py
      run: python snapshot_once.py

    # 5) Commit & push if the CSV changed
    - name: Commit and push CSV
      run: |
        git config --global user.name  "snapshot-bot"
        git config --global user.email "bot@example.com"
        # stage only if file modified
        if git status --porcelain agg_snapshot.csv | grep .; then
          git add agg_snapshot.csv
          git commit -m "auto snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
        else
          echo "No changes to commit"
        fi
