name: snapshot-once

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      # Checkout with write-enabled GITHUB_TOKEN
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests

      - name: Run snapshot script
        run: python snapshot_once.py

      - name: Commit & push CSV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "snapshot-bot"
          git config user.email "bot@example.com"

          # Always stage the CSV
          git add -A agg_snapshot.csv

          # Commit only if there is something new to commit
          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "auto snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # Push using the token for auth
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
