name: snapshot-once
on:
  workflow_dispatch:    
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install websockets
      - name: Install libs
        run: pip install requests pandas

      - run: python snapshot_once.py
      - run: |
          git config --global user.name  "bot"
          git config --global user.email "bot@none"
          git add agg_snapshot.csv
          git commit -m "auto $(date -u)" || echo "no change"
          git push
